version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-PAF-main
      dockerfile: Dockerfile
    ports:
      - "3001:80"  # 🔹 Servimos el frontend en el puerto 3001
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:3000  # 🔹 Cambia esto en tu nuxt.config.js

  backend:
    build:
      context: ./backend-PAF-main
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=alonsoreyes104
      - DB_NAME=personal
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy  # 🔹 Asegura que PostgreSQL está listo antes de arrancar el backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alonsoreyes104
      POSTGRES_DB: personal1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
