version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-PAF-main
      dockerfile: DockerFile
    ports:
      - "3001:3001"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend-PAF-main
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=alonsoreyes104
      - DB_NAME=personal
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alonsoreyes104
      POSTGRES_DB: personal1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: