version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-PAF-main
      dockerfile: Dockerfile
    ports:
      - "3001:80"  # Servimos el frontend en el puerto 3001
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:3000  # Cambia esto en tu nuxt.config.js

  backend:
    build:
      context: ./backend-PAF-main
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal  # Conéctate a la base de datos existente
      - DB_USER=postgres
      - DB_PASSWORD=alonsoreyes104
      - DB_NAME_PERSONAL=personal1
      - DB_PORT=5432