# Imagen base de Node.js
FROM node:20-alpine

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivos package.json y package-lock.json para instalar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos al contenedor
COPY . .

# Construir el proyecto para producción
RUN npm run build

# Exponer el puerto en el que correrá Nuxt (por defecto 3000)
EXPOSE 3001

# Comando para iniciar la aplicación en modo producción
CMD ["npm", "run", "start"]