# Paso 1: Construir la aplicación con Node.js
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run generate

# Verificar que los archivos se generaron
RUN ls -al /app/.output/public/

# Paso 2: Servir la aplicación con Nginx
FROM nginx:alpine

# Copiar los archivos estáticos al contenedor de Nginx
COPY --from=build /app/.output/public/. /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf


# Exponer el puerto 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
